# 降雨予測の基本設定ファイル

# モデル設定
model:
  name: RainfallPredictionModel
  params:
    input_dim: 13  # 特徴量の次元数（temperature, humidity, pressure, wind_speed）
    hidden_dims: [32, 16]
    output_dim: 1
    dropout_rate: 0.2

# データセット設定
dataset:
  data_path: tasks/BinaryRainfallPrediction/data/train.csv
  batch_size: 16
  num_workers: 2
  train_ratio: 0.8

# 学習設定
training:
  epochs: 50
  eval_interval: 1
  early_stopping: 10
  save_best: true
  save_last: true

# 損失関数
criterion:
  name: BCELoss
  params: {}

# オプティマイザ
optimizer:
  name: Adam
  params:
    lr: 0.001
    weight_decay: 0.0001

# 学習率スケジューラ
scheduler:
  name: ReduceLROnPlateau
  params:
    mode: min
    factor: 0.5
    patience: 5
    verbose: true

# 出力設定
output:
  base_dir: tasks/BinaryRainfallPrediction/output 