# デフォルト設定ファイル

# モデル設定
model:
  name: SimpleModel
  params:
    input_dim: 10
    hidden_dim: 128
    output_dim: 2

# データセット設定
dataset:
  batch_size: 32
  num_workers: 4
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

# 学習設定
training:
  epochs: 50
  eval_interval: 1
  early_stopping: 10
  save_best: true
  save_last: true

# 損失関数
criterion:
  name: CrossEntropyLoss
  params: {}

# オプティマイザ
optimizer:
  name: Adam
  params:
    lr: 0.001
    weight_decay: 0.0001

# 学習率スケジューラ
scheduler:
  name: ReduceLROnPlateau
  params:
    mode: min
    factor: 0.1
    patience: 5
    verbose: true

# ロギング設定
logging:
  log_interval: 10
  use_wandb: false
  wandb_project: experiment_management
  wandb_entity: null 